//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SosyalYardim.Module.BusinessObjects.Biz
{

    public partial class Hane : XPObject
    {
        decimal fEnlem;
        public decimal Enlem
        {
            get { return fEnlem; }
            set { SetPropertyValue<decimal>(nameof(Enlem), ref fEnlem, value); }
        }
        decimal fBoylam;
        public decimal Boylam
        {
            get { return fBoylam; }
            set { SetPropertyValue<decimal>(nameof(Boylam), ref fBoylam, value); }
        }
        string fUAVT;
        public string UAVT
        {
            get { return fUAVT; }
            set { SetPropertyValue<string>(nameof(UAVT), ref fUAVT, value); }
        }
        Lokasyon fLokasyon;
        [Association(@"HaneReferencesLokasyon")]
        public Lokasyon Lokasyon
        {
            get { return fLokasyon; }
            set { SetPropertyValue<Lokasyon>(nameof(Lokasyon), ref fLokasyon, value); }
        }
        [Association(@"KisiReferencesHane")]
        public XPCollection<Kisi> Kisiler { get { return GetCollection<Kisi>(nameof(Kisiler)); } }
    }

}
