//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SosyalYardim.Module.BusinessObjects.Biz
{

    public partial class Il : XPObject
    {
        string fAd;
        public string Ad
        {
            get { return fAd; }
            set { SetPropertyValue<string>(nameof(Ad), ref fAd, value); }
        }
        [Association(@"IlceReferencesIl")]
        public XPCollection<Ilce> Ilceler { get { return GetCollection<Ilce>(nameof(Ilceler)); } }
    }

}
