//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SosyalYardim.Module.BusinessObjects.Biz
{

    public partial class Kisi : XPObject
    {
        string fAd;
        public string Ad
        {
            get { return fAd; }
            set { SetPropertyValue<string>(nameof(Ad), ref fAd, value); }
        }
        string fSoyad;
        public string Soyad
        {
            get { return fSoyad; }
            set { SetPropertyValue<string>(nameof(Soyad), ref fSoyad, value); }
        }
        int fTCNo;
        public int TCNo
        {
            get { return fTCNo; }
            set { SetPropertyValue<int>(nameof(TCNo), ref fTCNo, value); }
        }
        Hane fHane;
        [Association(@"KisiReferencesHane")]
        public Hane Hane
        {
            get { return fHane; }
            set { SetPropertyValue<Hane>(nameof(Hane), ref fHane, value); }
        }
    }

}
