//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SosyalYardim.Module.BusinessObjects.Biz
{

    public partial class Teslimat : XPObject
    {
        Yardim fYardim;
        [Association(@"TeslimatReferencesYardim")]
        public Yardim Yardim
        {
            get { return fYardim; }
            set { SetPropertyValue<Yardim>(nameof(Yardim), ref fYardim, value); }
        }
        SosyalYardim.Module.BusinessObjects.ETeslimatDurum fDurum;
        public SosyalYardim.Module.BusinessObjects.ETeslimatDurum Durum
        {
            get { return fDurum; }
            set { SetPropertyValue<SosyalYardim.Module.BusinessObjects.ETeslimatDurum>(nameof(Durum), ref fDurum, value); }
        }
    }

}
