//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SosyalYardim.Module.BusinessObjects.Biz
{

    public partial class Yardim : XPObject
    {
        YardimTipi fYardimTipi;
        [Association(@"YardimReferencesYardimTipi")]
        public YardimTipi YardimTipi
        {
            get { return fYardimTipi; }
            set { SetPropertyValue<YardimTipi>(nameof(YardimTipi), ref fYardimTipi, value); }
        }
        Kisi fKisi;
        public Kisi Kisi
        {
            get { return fKisi; }
            set { SetPropertyValue<Kisi>(nameof(Kisi), ref fKisi, value); }
        }
        DateTime fTarihBaslangic;
        public DateTime TarihBaslangic
        {
            get { return fTarihBaslangic; }
            set { SetPropertyValue<DateTime>(nameof(TarihBaslangic), ref fTarihBaslangic, value); }
        }
        DateTime fTarihBitis;
        public DateTime TarihBitis
        {
            get { return fTarihBitis; }
            set { SetPropertyValue<DateTime>(nameof(TarihBitis), ref fTarihBitis, value); }
        }
        bool fAktif;
        public bool Aktif
        {
            get { return fAktif; }
            set { SetPropertyValue<bool>(nameof(Aktif), ref fAktif, value); }
        }
        [Association(@"TeslimatReferencesYardim")]
        public XPCollection<Teslimat> Teslimatlar { get { return GetCollection<Teslimat>(nameof(Teslimatlar)); } }
    }

}
